name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  percentage:  # id of input
    description: 'controlled percentage of the action passing'
    required: true
    default: '50'
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
